language: node_js

node_js: 10.16.0

services:
  - mongodb

before_script: 
  - sleep 15
  - mongo testcontacts --eval 'db.createUser({user:"testContact",pwd:"xyz123",roles:["readWrite"]});'

script: 
  - npm run test

after_success:
  - npm run coveralls